name: Build and Release

on:
  push:
    tags:
      - 'v0.1.0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: mac
          - os: ubuntu-22.04
            target: linux-rpm  # substitui o rpm pelo AppImage
          - os: ubuntu-22.04
            target: linux-deb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23

      - name: Build Installer
        run: ./gradlew jpackageInstaller
        env:
          TARGET_OS: ${{ matrix.target }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: app/build/jpackage/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
